# Read csv file

In [19]:
import pandas as pd

data = pd.read_csv('dataset - dataset.csv')

print(data)

    Order ID       Product Name             Category  Price  Quantity  \
0       1001          iPhone 12          Electronics    999         1
1       1002         Samsung TV          Electronics    599         2
2       1003       Canon Camera          Electronics    399         1
3       1004        Macbook Air          Electronics   1299         1
4       1005            T-Shirt             Clothing     20         5
5       1006      Running Shoes             Footwear    100         3
6       1007          Desk Lamp      Home and Garden     30         2
7       1008              Dress             Clothing     50         1
8       1009        Smart Watch          Electronics    199         1
9       1010            Toaster      Home and Garden     25         1
10      1011         Headphones          Electronics    199         3
11      1012            Monitor          Electronics    299         1
12      1013       Cookware Set      Home and Garden    149         1
13      1014     Microwave Oven          Electronics    149         1
14      1015            Blender      Home and Garden     49         2
15      1016    Smartphone Case          Electronics     20         3
16      1017           Sneakers             Footwear     80         2
17      1018       Dining Table      Home and Garden    499         1
18      1019             Jacket             Clothing     80         1
19      1020       Water Bottle      Home and Garden     10         5
20      1021      Ankle Weights  Sports and Outdoors     20         1
21      1022           Yoga Mat  Sports and Outdoors     30         1
22      1023           Backpack  Fashion Accessories     50         2
23      1024   Desktop Computer          Electronics    999         1
24      1025       Office Chair      Home and Garden    149         1
25      1026     Running Shorts             Clothing     40         2
26      1027  Bluetooth Speaker          Electronics     79         1
27      1028       Garden Tools      Home and Garden     30         1
28      1029     Baseball Glove  Sports and Outdoors     99         1
29      1030   Smart Thermostat      Home and Garden    149         1
30      1031      Back Massager  Health and Wellness     50         1
31      1032           Football  Sports and Outdoors     25         2
32      1033          Bookshelf      Home and Garden     99         1
33      1034         Sunglasses  Fashion Accessories     25         1
34      1035   Wireless Earbuds          Electronics    129         1
35      1036      Running Socks  Sports and Outdoors     10         5
36      1037             Blouse             Clothing     40         1
37      1038   Swimming Goggles  Sports and Outdoors     30         1
38      1039      Smart Speaker          Electronics     99         1
39      1040             Kettle      Home and Garden     25         1

    Discount  Order Date          Customer Email Customer Gender  \
0       0.10  01-01-2022      john.doe@gmail.com            Male
1       0.00  01-01-2022      jane.doe@gmail.com          Female
2       0.05  02-01-2022      john.doe@gmail.com            Male
3       0.20  02-01-2022    john.smith@gmail.com            Male
4       0.05  03-01-2022   susan.smith@gmail.com          Female
5       0.00  04-01-2022  jack.johnson@gmail.com            Male
6       0.00  04-01-2022   emily.jones@gmail.com          Female
7       0.00  05-01-2022   amy.johnson@gmail.com          Female
8       0.00  05-01-2022    will.smith@gmail.com            Male
9       0.05  06-01-2022    john.smith@gmail.com            Male
10      0.10  07-01-2022      jane.doe@gmail.com          Female
11      0.05  07-01-2022      john.doe@gmail.com            Male
12      0.00  08-01-2022   emily.smith@gmail.com          Female
13      0.00  08-01-2022    jack.jones@gmail.com            Male
14      0.00  09-01-2022   amy.johnson@gmail.com          Female
15      0.05  09-01-2022    john.smith@gmail.com            Male
16      0.00  10-01-2022  jack.johnson@gmail.com            Male
17      0.10  10-01-2022   emily.jones@gmail.com          Female
18      0.00  11-01-2022   susan.smith@gmail.com          Female
19      0.00  12-01-2022    will.smith@gmail.com            Male
20      0.00  22-01-2022    will.smith@gmail.com            Male
21      0.00  12-01-2022    jack.jones@gmail.com            Male
22      0.00  13-01-2022   emily.smith@gmail.com          Female
23      0.00  13-01-2022    will.smith@gmail.com            Male
24      0.00  14-01-2022      john.doe@gmail.com            Male
25      0.00  14-01-2022  jack.johnson@gmail.com            Male
26      0.05  15-01-2022      jane.doe@gmail.com          Female
27      0.00  15-01-2022    john.smith@gmail.com            Male
28      0.00  16-01-2022   susan.smith@gmail.com          Female
29      0.10  16-01-2022   amy.johnson@gmail.com          Female
30      0.00  17-01-2022    jack.jones@gmail.com            Male
31      0.00  17-01-2022  jack.johnson@gmail.com            Male
32      0.00  18-01-2022   emily.jones@gmail.com          Female
33      0.00  18-01-2022   emily.smith@gmail.com          Female
34      0.00  19-01-2022      jane.doe@gmail.com          Female
35      0.00  19-01-2022    will.smith@gmail.com            Male
36      0.00  20-01-2022   susan.smith@gmail.com          Female
37      0.00  20-01-2022    john.smith@gmail.com            Male
38      0.00  21-01-2022    jack.jones@gmail.com            Male
39      0.00  21-01-2022   emily.smith@gmail.com          Female

    Customer Age Customer State
0             30     California
1             35     California
2             30     California
3             25          Texas
4             45        Florida
5             28       New York
6             22          Texas
7             35        Florida
8             50     California
9             25          Texas
10            35     California
11            30     California
12            40          Texas
13            32        Florida
14            35        Florida
15            25          Texas
16            28       New York
17            22          Texas
18            45        Florida
19            50     California
20            50     California
21            32        Florida
22            40          Texas
23            50     California
24            30     California
25            28       New York
26            35     California
27            25          Texas
28            45        Florida
29            35        Florida
30            32        Florida
31            28       New York
32            22          Texas
33            40          Texas
34            35     California
35            50     California
36            45        Florida
37            25          Texas
38            32        Florida
39            40          Texas

# central tendency

In [20]:
print(data.mean())

Order ID        1020.5000
Price            185.7750
Quantity           1.6250
Discount           0.0225
Customer Age      34.6500
dtype: float64

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12456\2101390418.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(data.mean())

In [21]:
print(data.median())

Order ID        1020.5
Price             79.5
Quantity           1.0
Discount           0.0
Customer Age      33.5
dtype: float64

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12456\2279890642.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(data.median())

In [22]:
data.mode()

,Order ID,Product Name,Category,Price,Quantity,Discount,Order Date,Customer Email,Customer Gender,Customer Age,Customer State
0,1001,Ankle Weights,Electronics,25.0,1.0,0.0,01-01-2022,john.smith@gmail.com,Male,35.0,California
1,1002,Back Massager,NaN,30.0,NaN,NaN,02-01-2022,will.smith@gmail.com,NaN,NaN,NaN
2,1003,Backpack,NaN,149.0,NaN,NaN,04-01-2022,NaN,NaN,NaN,NaN
3,1004,Baseball Glove,NaN,NaN,NaN,NaN,05-01-2022,NaN,NaN,NaN,NaN
4,1005,Blender,NaN,NaN,NaN,NaN,07-01-2022,NaN,NaN,NaN,NaN
5,1006,Blouse,NaN,NaN,NaN,NaN,08-01-2022,NaN,NaN,NaN,NaN
6,1007,Bluetooth Speaker,NaN,NaN,NaN,NaN,09-01-2022,NaN,NaN,NaN,NaN
7,1008,Bookshelf,NaN,NaN,NaN,NaN,10-01-2022,NaN,NaN,NaN,NaN
8,1009,Canon Camera,NaN,NaN,NaN,NaN,12-01-2022,NaN,NaN,NaN,NaN
9,1010,Cookware Set,NaN,NaN,NaN,NaN,13-01-2022,NaN,NaN,NaN,NaN
10,1011,Desk Lamp,NaN,NaN,NaN,NaN,14-01-2022,NaN,NaN,NaN,NaN
11,1012,Desktop Computer,NaN,NaN,NaN,NaN,15-01-2022,NaN,NaN,NaN,NaN
12,1013,Dining Table,NaN,NaN,NaN,NaN,16-01-2022,NaN,NaN,NaN,NaN
13,1014,Dress,NaN,NaN,NaN,NaN,17-01-2022,NaN,NaN,NaN,NaN
14,1015,Football,NaN,NaN,NaN,NaN,18-01-2022,NaN,NaN,NaN,NaN
15,1016,Garden Tools,NaN,NaN,NaN,NaN,19-01-2022,NaN,NaN,NaN,NaN
16,1017,Headphones,NaN,NaN,NaN,NaN,20-01-2022,NaN,NaN,NaN,NaN
17,1018,Jacket,NaN,NaN,NaN,NaN,21-01-2022,NaN,NaN,NaN,NaN
18,1019,Kettle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1020,Macbook Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1021,Microwave Oven,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1022,Monitor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1023,Office Chair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1024,Running Shoes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1025,Running Shorts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1026,Running Socks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1027,Samsung TV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1028,Smart Speaker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1029,Smart Thermostat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1030,Smart Watch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,1031,Smartphone Case,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,1032,Sneakers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,1033,Sunglasses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,1034,Swimming Goggles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,1035,T-Shirt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,1036,Toaster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,1037,Water Bottle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,1038,Wireless Earbuds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,1039,Yoga Mat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,1040,iPhone 12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#  dispersion

In [23]:
data.std()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12456\2723740006.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.std()

Order ID         11.690452
Price           296.258938
Quantity          1.147740
Discount          0.043780
Customer Age      8.710589
dtype: float64

In [24]:
data.skew()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12456\1188251951.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.skew()

Order ID        0.000000
Price           2.583128
Quantity        2.086982
Discount        2.331605
Customer Age    0.445661
dtype: float64

# Use iteration and sorting to find the top 10 most popular products by quantitysold.

In [25]:
sorted_products = sorted(data, key=lambda x: x[1], reverse=True)

In [11]:
for i in range(10):
    print(sorted_products[i][0], ":", sorted_products[i][1])

products = [("Product A", 100), ("Product B", 50), ("Product C", 200), ("Product D", 75), ("Product E", 150)]

sorted_products = sorted(data, key=lambda x: x[1], reverse=True)

for i in range(10):
    print(sorted_products[i][0], ":", sorted_products[i][1])

Q : u
C : u
C : u
C : u
C : u
O : r
P : r
P : r
O : r
D : i
Q : u
C : u
C : u
C : u
C : u
O : r
P : r
P : r
O : r
D : i

# Use indexing and selecting data techniques to filter the dataset for ordersplaced on date 01-01-2022 and for customers who live in California.

In [27]:
data['Order Date'] = pd.to_datetime(data['Order Date'])

In [29]:
jan_1_orders = data[data['Order Date'] == '2022-01-01']

In [33]:
california_orders = jan_1_orders[jan_1_orders['CustomerState'] == 'California']

KeyError: 'CustomerState'

In [15]:


california_orders = jan_1_orders[jan_1_orders['Customer State'] == 'California']
print(california_orders)

   Order ID Product Name     Category  Price  Quantity  Discount Order Date  \
0      1001    iPhone 12  Electronics    999         1       0.1 2022-01-01
1      1002   Samsung TV  Electronics    599         2       0.0 2022-01-01

       Customer Email Customer Gender  Customer Age Customer State
0  john.doe@gmail.com            Male            30     California
1  jane.doe@gmail.com          Female            35     California

# Usestatistical functions to calculate the correlation between Price andQuantity, and between Discount and Quantity. Interpret the results.

In [16]:
frame = pd.DataFrame(data)
print( frame['Price'].corr(frame['Quantity']))
print (frame.corr())

-0.224217756612051
              Order ID     Price  Quantity  Discount  Customer Age
Order ID      1.000000 -0.424731 -0.153835 -0.400794      0.146800
Price        -0.424731  1.000000 -0.224218  0.631238     -0.092676
Quantity     -0.153835 -0.224218  1.000000 -0.031893      0.271222
Discount     -0.400794  0.631238 -0.031893  1.000000     -0.301562
Customer Age  0.146800 -0.092676  0.271222 -0.301562      1.000000

In [17]:
frame = pd.DataFrame(data)
print( frame['Discount'].corr(frame['Quantity']))
print (frame.corr())

-0.031893229748917944
              Order ID     Price  Quantity  Discount  Customer Age
Order ID      1.000000 -0.424731 -0.153835 -0.400794      0.146800
Price        -0.424731  1.000000 -0.224218  0.631238     -0.092676
Quantity     -0.153835 -0.224218  1.000000 -0.031893      0.271222
Discount     -0.400794  0.631238 -0.031893  1.000000     -0.301562
Customer Age  0.146800 -0.092676  0.271222 -0.301562      1.000000

# Create visualizations to explore the relationship between Customer Age and OrderDate, and between Category and Quantity. Include appropriate labels and
.

In [18]:
import pandas as pd
import matplotlib.pyplot as plt
plt.scatter(orders['CustomerAge'], orders['OrderDate'])
plt.xlabel('Customer Age')
plt.ylabel('Order Date')
plt.title('Relationship between Customer Age and Order Date')
plt.show()

NameError: name 'orders' is not defined